version: "3"

services:
  app:
    container_name: quickstarter-server
    restart: always
    build: .
    ports:
      - "80:8082"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: quickstarter-mongo
    image: mongo
    ports:
      - "27017:27017"
