version: "3"

services:
  app:
    container_name: quickstarter-server
    restart: always
    build: .
    ports:
      - "8082:8082"
    links:
      - mongo
  mongo:
    container_name: quickstarter-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
